src/__init__.py
import os
from flask import Flask, render_template

from .views import avistamento, avistamento

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'mabuya.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from .data import db
    db.init_app(app)

    from .views import sobre, avistamento, especies
    app.register_blueprint(avistamento.bp)
    app.register_blueprint(sobre.bp)
    app.register_blueprint(especies.bp)

    @app.route('/')
    def home():
        return render_template('home.html')

    return app

src/views/avistamento.py
from flask import Blueprint, redirect, render_template, request, session, url_for
from src.data.db import get_db

#Cria a blueprint do módulo de avistamentos
bp = Blueprint('avistamento', __name__, url_prefix='/avistamento')


@bp.route('/novo', methods=('GET', 'POST'))
#CREATE
def criar():

    if request.method == 'POST':

        #Lê formulário
        especie = request.form ['especie']
        local = request.form ['local']
        comentario = request.form ['comentario']

        #Chama o banco de dados e insere valores
        db = get_db()
        db.execute(
            'INSERT INTO avistamento (nome_especie, local_avistamento, comentario) VALUES (?, ?, ?)',
            (especie, local, comentario)
        )
        db.commit()

        #Redireciona para página com todos os avistamentos
        return redirect(url_for('avistamento.ler'))

    #Renderiza a página de cadastrar um avistamento
    return render_template('avistamento/criar.html')


@bp.route('/todos')
#LER
def ler():
        
    #Chama o banco de dados e coleta valores de todos os avistamentos cadastrados
    db = get_db()
    avistamentos = db.execute(
        'SELECT * FROM avistamento ORDER BY data_avistamento DESC'
    ).fetchall()
    
    #Renderiza a página com todos os avistamentos
    return render_template('avistamento/leitura.html', avistamentos=avistamentos)


#COLETAR AVISTAMENTO POR ID
def get_avistamento(id):

    #Chama o banco de dados e coleta valores de um avistamento específico
    db = get_db()
    avistamento = db.execute(
        'SELECT * FROM avistamento WHERE id = ?', (id,)
    ).fetchone()

    return avistamento
 

@bp.route('/<int:id>/editar', methods=('GET', 'POST'))
#EDITAR
def editar(id):

    #Identifica e seleciona o avistamento
    avistamento = get_avistamento(id)

    if request.method == 'POST':
        #Lê formulário
        especie = request.form ['especie']
        local = request.form ['local']
        comentario = request.form ['comentario']

        #Chama o banco de dados e edita valores
        db = get_db()
        db.execute(
            'UPDATE avistamento SET nome_especie = ?, local_avistamento = ?, comentario = ? WHERE id = ?',
            (especie, local, comentario, id)
        )
        db.commit()

        #Redireciona para página com todos os avistamentos
        return redirect(url_for('avistamento.ler'))
    
    #Renderiza página de editar um avistamento
    return render_template('avistamento/editar.html', avistamento=avistamento)


@bp.route('/<int:id>/deletar')
#DELETAR
def deletar(id):

    #Identifica e seleciona o avistamento
    get_avistamento(id)

    #Chama o banco de dados e edita valores
    db = get_db()
    db.execute(
        'DELETE FROM avistamento WHERE id = ?', (id,)
        )
    db.commit()

    return redirect(url_for('avistamento.ler'))

src/views/especies.py
from flask import Blueprint, redirect, render_template, request, session, url_for
from src.data.db import get_db

#Cria a blueprint do módulo de avistamentos
bp = Blueprint('especies', __name__, url_prefix='/especies')

@bp.route('/<nome>')
def especie(nome):
    db = get_db()
    especie = db.execute(
        'SELECT * FROM especime WHERE nome_popular = ? COLLATE NOCASE', (nome,)
        ).fetchone()
    
    return render_template('especies.html', especie = especie)

src/views/sobre.py
from flask import Blueprint, redirect, render_template, request, session, url_for

bp = Blueprint('sobre', __name__, url_prefix='/about')

@bp.route('/')
def sobre():
    return render_template('sobre.html')

src/templates/avistamento/criar.html
{% extends 'base.html' %}
{% block title %}Contribua{% endblock %}

{% block content %}
<div class="criar-container flex">
    <div class="form-container flex column">
        <div>
            <h2>Compartilhe seu avistamento</h2>
        </div>
        <form action="" method="POST" class="flex column">
            <div class="flex column">
                <label for="especie">Espécie</label>
                <select name="especie" id="especie" required>
                    <option value="Mabuya">Mabuya</option>
                    <option value="Sebito">Sebito</option>
                    <option value="Cocoruta">Cocoruta</option>
                    <option value="Gameleira">Gameleira</option>
                    <option value="Ribaça">Ribaça</option>
                </select>
            </div>
        
            <div class="flex column">
                <label for="local">Local do avistamento</label>
                <input type="text" name="local" required>
            </div>
    
            <div class="flex column">
                <label for="comentario">Descrição</label>
                <textarea name="comentario" id="comentario" required></textarea>
            </div>
    
            <div class="flex column">
                <button type="submit">Enviar</button>
            </div>
        </form>
    </div>
    
    <div class="instrucao-container flex column">
        <h2>Instruções</h2>
        <p>
            Ao avistar uma espécie, preencha no formulário ao lado o nome (dentre as opções de espécies catalogadas pelo projeto), 
            o local em que foi avistada e uma descrição contendo o máximo de detalhes possíveis.
        </p>

        <p>
            Ficou com alguma dúvida sobre a espécie avistada? Acesse nossas espécies catalogadas para ver fotos e descrição de cada uma.
        </p>

        <p>Sua contribuição é muito importante para ajudar a mapear as espécies endêmicas de Fernando de Noronha!</p>

        <form action="">
            <button formaction="{{url_for('especies.especie', nome = 'mabuya')}}">Ver espécies</button>
        </form>
    </div>
</div>


{% endblock %}

src/templates/avistamento/editar.html
{% extends 'base.html' %}
{% block title %}Editar avistamento{% endblock %}

{% block content %}

<div class="edit-container flex column">
    <div>
        <h2>Edite seu avistamento</h2>
    </div>
    <form action="" method="POST" class="flex column">
        <div class="flex column">
            <label for="especie">Espécie</label>
            <select name="especie" id="especie"  required>
                <option value="Mabuya" {% if avistamento['nome_especie'] == 'Mabuya' %} selected {% endif %}>Mabuya</option>
                <option value="Sebito" {% if avistamento['nome_especie'] == 'Sebito' %} selected {% endif %}>Sebito</option>
                <option value="Cocoruta" {% if avistamento['nome_especie'] == 'Cocoruta' %} selected {% endif %}>Cocoruta</option>
                <option value="Gameleira" {% if avistamento['nome_especie'] == 'Gameleira' %} selected {% endif %}>Gameleira</option>
                <option value="Ribaça" {% if avistamento['nome_especie'] == 'Ribaça' %} selected {% endif %}>Ribaça</option>
            </select>
        </div>
    
        <div class="flex column">
            <label for="local">Local do avistamento</label>
            <input type="text" name="local" value="{{ avistamento['local_avistamento'] }}" required>
        </div>

        <div class="flex column">
            <label for="comentario">Descrição</label>
            <textarea name="comentario" id="comentario" required>{{ avistamento['comentario'] }}</textarea>
        </div>

        <div class="flex column">
            <button type="submit">Enviar</button>
        </div>
    </form>
    
 </div>

{% endblock %}

src/templates/avistamento/leitura.html
{% extends 'base.html' %}
{% block title %}Avistamentos{% endblock %}

{% block content %}
    <div class="avistamento-container flex column">
        <h2>Avistamentos</h2>

        {% for avistamento in avistamentos %}
            <article class="avistamento-post flex column">

                <div class="flex avistamento-header">
                    <h4>
                        <a href="{{ url_for('especies.especie', nome = avistamento['nome_especie']) }}">{{avistamento['nome_especie']}}</a>
                    </h4>
                    <div class="flex editar-excluir">
                        <a href="{{ url_for('avistamento.editar', id = avistamento['id']) }}">Editar</a>
                        <a href="{{ url_for('avistamento.deletar', id = avistamento['id']) }}">Excluir</a>
                    </div>
                    
                </div>

                <div class="local-data flex">
                    <div class="local-avistamento">{{avistamento['local_avistamento']}},</div>
                    <div>em {{avistamento['data_avistamento'].strftime('%d/%m/%Y')}}</div>
                </div>
            
                <div class="avistamento-comentario">{{avistamento['comentario']}}</div>
            </article>
        {% endfor %}
    </div>
    

{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - Projeto Mabuya</title>

    <!--Fontes-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!--CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='app.css') }}">
</head>

<header>
    <nav class="navbar flex">
        <div class="nav-blocks flex">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Projeto Mabuya" style="width:20%;">
        </div>
        <div class="nav-blocks flex">
            <a href="{{ url_for('home') }}">Home</a>
            <a href="{{ url_for('especies.especie', nome = 'mabuya') }}">Espécies</a>
            <a href="{{ url_for('avistamento.ler')}}">Avistamentos</a>
            <a href="{{ url_for('avistamento.criar')}}">Contribua</a>
            <a href="{{ url_for('sobre.sobre') }}">Sobre Nós</a>
        </div>
    </nav>
</header>

<body> 
{% block content %}
{% endblock %}
</body>
</html>

src/templates/especies.html
{% extends 'base.html' %}
{% block title %}Espécies{% endblock %}
{% block content %}
    <div class="especies-container flex column">
        <form action="" class="especies-container flex">
            <button formaction="{{url_for('especies.especie', nome = 'mabuya')}}" class="especie-button">Mabuya</button>
            <button formaction="{{url_for('especies.especie', nome = 'sebito')}}" class="especie-button">Sebito</button>
            <button formaction="{{url_for('especies.especie', nome = 'cocoruta')}}" class="especie-button">Cocoruta</button>
            <button formaction="{{url_for('especies.especie', nome = 'gameleira')}}" class="especie-button">Gameleira</button>
            <button formaction="{{url_for('especies.especie', nome = 'ribaça')}}" class="especie-button">Ribaça</button>
        </form>

        <div class="especie flex column">
            <div class="flex" style="gap: 30px;">
                <div class="especie-foto">
                    {% if especie['nome_popular'] == 'Mabuya' %}
                    <img src="{{ url_for('static', filename='images/mabuya.webp') }}" alt="Lagarto mabuia em cima de uma pedra." style="width: 100%;">
                    {% elif especie['nome_popular'] == 'Sebito' %}
                    <img src="{{ url_for('static', filename='images/sebito.jpg') }}" alt="Lagarto sebito no tronco de uma árvore." style="width: 100%;">
                    {% elif especie['nome_popular'] == 'Cocoruta' %}
                    <img src="{{ url_for('static', filename='images/cocoruta.jpeg') }}" alt="Pássaro cocoruta em um galho com espinhos." style="width: 100%;">
                    {% elif especie['nome_popular'] == 'Gameleira' %}
                    <img src="{{ url_for('static', filename='images/gameleira.jpg') }}" alt="Árvore gameleira." style="width: 100%;">
                    {% elif especie['nome_popular'] == 'Ribaça' %}
                    <img src="{{ url_for('static', filename='images/ribaça.jpg') }}" alt="Pássaro ribaça em cima de um galho." style="width: 100%;">
                    {% endif %}
                </div>
    
                <div class="especie-info flex column">
                    <h3>{{especie['nome_popular']}}</h3><br>
                    <div>Nome científico: {{especie['nome_cientifico']}}</div>
                    <div>Família: {{especie['familia']}}</div>
                    <div>Ordem: {{especie['ordem']}}</div>
                    <div>Classe: {{especie['classe']}}</div>
                    <div>Filo: {{especie['filo']}}</div>
                    <div>Reino: {{especie['reino']}}</div>
                </div>
            </div>
            
            <div>{{especie['descricao']}}</div>
        </div>
    </div>
{% endblock %}

src/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}

<div class="home-banner flex">
    <div class="home-banner-content flex column">
        <h1>Projeto Mabuya</h1>
        <p>
            Ajude a monitorar espécies endêmicas da Ilha de Fernando de Noronha cadastrando seu avistamento.
        </p>
        <form action="">
            <button formaction=" {{ url_for('avistamento.criar') }} ">Conheça</button>
        </form>
    </div>
    <img src="{{url_for('static', filename='images/home_img.jpg')}}" alt="Ilustração de uma paisagem com curso d'água e floresta." style="width: 35%;">
</div>

{% endblock %}

src/templates/sobre.html
{% extends 'base.html' %}
{% block title %}Sobre Nós{% endblock %}
{% block content %}
    <div class="sobre-container">
        <h2>Quem somos?</h2><br>
        <p>
            O Projeto Mabuya é uma iniciativa coletiva de discentes da Universidade Federal Rural de Pernambuco 
            no monitoramento das espécies endêmicas do Arquipélago de Fernando de Noronha.
        </p><br>
    
        <h2>O que fazemos?</h2><br>
        <p>
            A proposta se estrutura na colaboração pública para a coleta de dados, através do registro de avistamentos das espécies por qualquer pessoa
             ou entidade, e na estruturação de um banco de informações acerca da fauna e flora. Além disso, oferecemos a possibilidade de o visitante
            conhecer e saber mais sobre cada espécie, com informações ecológicas que disponibilizamos no site.
        </p><br>
        <p>
            A base de dados construída com a participação popular possibilita o desenvolvimento de diversos mecanismos que possam contribuir para a
            preservação da natureza, como a elaboração de estudos e pesquisas, políticas públicas de proteção ambiental, e conscientização e educação 
            ecológica.
        </p><br>

        <h2>Por que fazemos?</h2><br>
        <p>
            O Arquipélago de Fernando de Noronha possui como principais elementos de perturbações ambientais: turismo, empreendimentos imobiliários 
            e atividades extrativistas, como a pesca.
        </p><br>
        <p>
            A importância do monitoramento de espécies endêmicas surge da maior vulnerabilidade à extinção dessa categoria frente a essas perturbações
            ambientais, em relação a espécies não endêmicas, devido à distribuição geográfica limitada e à baixa densidade populacional.
        </p><br>
        <p>
            Acreditamos que a união da ciência feita dentro da universidade com a sociedade em contato com o meio ambiente potencializa o objetivo 
            e interesse comum de todos na conservação ambiental.
        </p>
        </div>
    
{% endblock %}